version: '3.8'

services:
  web:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
      - ./services/web/index/:/usr/src/app/index/
    ports:
      - "5000:5000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: bitnami/postgresql:11.14.0-debian-10-r44
    ports:
      - "5432:5432"
    volumes:
      - ./services/persistence/db/:/bitnami/postgresql
    env_file:
      - ./.env.dev

volumes:
  postgres_data: